---
name: Test & Deploy

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 6,18 * * *"



jobs:
  test_repo:
    name: Test on MacOS w/ Py${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    steps:
    - name: Setup Python ${{ matrix.python-version }} env
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Ensure latest pip & wheel
      run: "python -m pip install -q --upgrade pip wheel"
    - name: Install dependencies
      run: |
        brew install zeromq flatbuffers
        sudo wget https://raw.githubusercontent.com/zeromq/cppzmq/v4.3.0/zmq.hpp -P \
          /usr/local/include
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Install from repo in test mode
      run: "pip install -e '.[dev]'"
    - name: Run tests
      run: "python -m pytest nle/tests"

  test_sdist:
    name: Test sdist on MacOS w/ Py3.8
    needs: test_repo
    runs-on: macos-latest
    steps:
    - name: Setup Python 3.8 env
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Ensure latest pip & wheel
      run: "python -m pip install -q --upgrade pip wheel"
    - name: Install deps
      run: |
        brew install zeromq flatbuffers
        sudo wget https://raw.githubusercontent.com/zeromq/cppzmq/v4.3.0/zmq.hpp -P \
          /usr/local/include
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Generate sdist
      run: |
       NLE_RELEASE_BUILD=1 python setup.py sdist
    - name: Install from sdist
      run: |
        SDISTNAME=$(ls dist/)
        MODE="[all]"
        pip install "dist/$SDISTNAME$MODE"
    - name: Run tests
      run: |
        REPONAME=$(basename $PWD)
        cd ..
        python -m pytest $REPONAME/nle/tests

  # deploy_sdist:
  #   if: startsWith( github.ref, "v" )
  #   needs: build_sdist
...
